info:
  app:
    name: zdb-portal-ui
    version: 1.0.0-SNAPSHOT
    description: ZDB PORTAL UI
---
spring:
  profiles:
    active: local
  thymeleaf:
     encoding: UTF-8
     
server:
  port: 8181
  
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true

---
spring:
  profiles: local

zdb-api-server:
  url: http://127.0.0.1:8080

zdb-demon-server:
  url: http://agent.zdb-dev.jp-tok.containers.mybluemix.net
  
props:
  appName: zdb-portal-local
  keycloak:
    zcp:
      clientId: account
      clientSecret: 71ad1e42-d239-4a7d-99f9-e1e50ad7ca93
      accessTokenUri: https://pog-dev-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: https://pog-dev-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
      redirectUri: ${HOME_URL:http://localhost:8181}/login
  iam:
    baseUrl: https://pog-dev-internal-iam.cloudzcp.io:443

cloudzcp:
  url: https://pog-dev-console.cloudzcp.io
grafana:
  url: http://grafana-zdb.cloudzcp.io
---  
spring:    
  devtools:
    livereload:
      enabled : true

---
spring:
  profiles: zdb-dev
server:
  port: 8080
zdb-api-server:
  url: http://api.${spring.profiles}.jp-tok.containers.mybluemix.net

logging:
  config: classpath:logback-prod.xml  
  
zdb-demon-server:
  url: http://agent.${spring.profiles}.jp-tok.containers.mybluemix.net

props:
  appName: zdb-portal
  keycloak:
    zcp:
      clientId: account
      clientSecret: 71ad1e42-d239-4a7d-99f9-e1e50ad7ca93
      accessTokenUri: https://pog-dev-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: https://pog-dev-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
      redirectUri: ${HOME_URL:http://console.${spring.profiles}.jp-tok.containers.mybluemix.net}/login
  iam:
    baseUrl: https://pog-dev-internal-iam.cloudzcp.io:443

cloudzcp:
  url: https://pog-dev-console.cloudzcp.io
grafana:
  url: http://pog-dev-zdb-monitoring.cloudzcp.io

  
---
spring:
  profiles: prod
server:
  port: 8080
zdb-api-server:
  url: ${api.server}

logging:
  config: classpath:logback-prod.xml  
  
zdb-demon-server:
  url: http://zdb-backup-agent-loadbalancer.zdb-system:8080

props:
  appName: zdb-portal-ui
  keycloak:
    zcp:
      clientId: account
      clientSecret: ${iam.secret}
      accessTokenUri: https://${iam.domain}.${domain.custom}/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: https://${iam.domain}.${domain.custom}/auth/realms/zcp/protocol/openid-connect/auth
      redirectUri: https://${zdb.domain}.${domain.custom}/login
  iam:
    baseUrl: http://zcp-iam.zcp-system

cloudzcp:
  url: https://${zcp.domain}.${domain.custom}
grafana:
  url: https://${grafana.domain}.${domain.custom}