info:
  app:
    name: zdb-portal-ui
    version: 1.2.2
    description: ZDB PORTAL UI

---
spring:
  profiles: native

zdb-api-server:
  url: http://localhost:8080

zdb-demon-server:
  url: http://agent.zdb-dev.jp-tok.containers.mybluemix.net

zdb:
  mariadb:
    version: 10.3.16, 10.2.21, 10.2.14
  redis: 
    version: 4.0.9

cluster: native

props:
  appName: zdb-portal-local
  keycloak:
    zcp:
      clientId: account
      clientSecret: 71ad1e42-d239-4a7d-99f9-e1e50ad7ca93
      accessTokenUri: https:/iam.native.skcloud.io/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: https://iam.native.skcloud.io/auth/realms/zcp/protocol/openid-connect/auth
      redirectUri: http://localhost:8181/login
  iam:
    baseUrl: https://internal-iam.native.skcloud.io

cloudzcp:
  url: https://console.native.skcloud.io
grafana:
  url: https://zdb-monitoring.native.skcloud.io
  
---
spring:
  profiles: prod
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    protocol_header: x-forwarded-proto  
  servlet:
    session:
      timeout: 3600
  error:
    whitelabel:
      enabled: false
        
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
    env:
     enabled: false   
zdb-api-server:
  url: ${api.server}

cluster: ${cluster}

zdb:
  mariadb:
    version: ${zdb.mariadb.version}
  redis: 
    version: ${zdb.redis.version}
    
logging:
  config: classpath:logback-prod.xml  
  
zdb-demon-server:
  url: http://zdb-backup-agent-loadbalancer.zdb-system:8080

props:
  appName: zdb-portal-ui
  keycloak:
    zcp:
      clientId: account
      clientSecret: ${iam.secret}
      accessTokenUri: https://${iam.domain}.${domain.custom}/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: https://${iam.domain}.${domain.custom}/auth/realms/zcp/protocol/openid-connect/auth
      redirectUri: https://${zdb.domain}.${domain.custom}/login
  iam:
    baseUrl: http://zcp-iam.zcp-system

cloudzcp:
  url: https://${zcp.domain}.${domain.custom}
grafana:
  url: https://${grafana.domain}.${domain.custom}