info:
  app:
    name: zdb-portal-ui
    version: 1.0.0-SNAPSHOT
    description: ZDB PORTAL UI
---
spring:
  profiles:
    active: local
  thymeleaf:
     encoding: UTF-8
     
server:
  port: 8181
  
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true

---
spring:
  profiles: local

zdb-api-server:
  url: http://127.0.0.1:8080

zdb-demon-server:
  url: http://agent.zdb-dev.jp-tok.containers.mybluemix.net
  
props:
  appName: zdb-portal-local
  keycloak:
    zcp:
      clientId: account
      clientSecret: 0227b024-6483-4e96-827b-3bc4dd73637e
      accessTokenUri: https://keycloak.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: https://keycloak.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
      redirectUri: ${HOME_URL:http://localhost:8181}/k8s-login
  iam:
    baseUrl: https://zcp-iam.cloudzcp.io:443

grafana:
  url: http://grafana-zdb.cloudzcp.io
---  
spring:    
  devtools:
    livereload:
      enabled : true

---
spring:
  profiles: zdb-dev
server:
  port: 8080
zdb-api-server:
  url: http://api.${spring.profiles}.jp-tok.containers.mybluemix.net

logging:
  config: classpath:logback-prod.xml  
  
zdb-demon-server:
  url: http://agent.${spring.profiles}.jp-tok.containers.mybluemix.net

props:
  appName: zdb-portal
  keycloak:
    zcp:
      clientId: account
      clientSecret: 0227b024-6483-4e96-827b-3bc4dd73637e
      accessTokenUri: https://keycloak.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: https://keycloak.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
      redirectUri: ${HOME_URL:http://console.${spring.profiles}.jp-tok.containers.mybluemix.net}/k8s-login
  iam:
    baseUrl: https://zcp-iam.cloudzcp.io:443

grafana:
  url: http://grafana-zdb.cloudzcp.io
---
spring:
  profiles: zcp-demo
server:
  port: 8080
zdb-api-server:
  url: http://api.${spring.profiles}.jp-tok.containers.mybluemix.net

logging:
  config: classpath:logback-prod.xml  
  
zdb-demon-server:
  url: http://agent.${spring.profiles}.jp-tok.containers.mybluemix.net

props:
  appName: zdb-portal
  keycloak:
    zcp:
      clientId: account
      clientSecret: 0227b024-6483-4e96-827b-3bc4dd73637e
      accessTokenUri: https://keycloak.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: https://keycloak.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
#      redirectUri: ${HOME_URL:http://console.${spring.profiles}.jp-tok.containers.mybluemix.net}/k8s-login
      redirectUri: http://zdb.cloudzcp.io/k8s-login
  iam:
    baseUrl: https://zcp-iam.cloudzcp.io:443

grafana:
  url: http://grafana-zdb.cloudzcp.io
  
---
spring:
  profiles: prod
server:
  port: 8080
zdb-api-server:
  url: ${zdb.portal.server.url}

logging:
  config: classpath:logback-prod.xml  
  
zdb-demon-server:
  url: ${zdb.backup.agent.url}

props:
  appName: zdb-portal-ui
  keycloak:
    zcp:
      clientId: account
      clientSecret: ${zcp.client.secret}
      accessTokenUri: ${zcp.access.token.url}
      userAuthorizationUri: ${zcp.user.auth.url}
      redirectUri: ${zcp.redirect.url}
  iam:
    baseUrl: ${iam.baseUrl}

grafana:
  url: ${grafana.url}  