apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  name: zdb-portal-ui-ingress
  namespace: zdb-system
spec:
  rules:
  - host: zdb.cloudzcp.io
    http:
      paths:
      - backend:
          serviceName: zdb-portal-ui-service
          servicePort: 8080
        path: /
